CREATE TABLE chat_message_reaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    message_id BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_chat_message_reaction PRIMARY KEY (id)
);

ALTER TABLE chat_message_reaction
    ADD CONSTRAINT uk_chat_message_reaction_message_id_member_id UNIQUE (message_id, member_id);

CREATE INDEX idx_chat_message_reaction_room_id ON chat_message_reaction (room_id);
