CREATE TABLE admin_action
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    actor_id   BIGINT                                  NOT NULL,
    action     VARCHAR(255)                            NOT NULL,
    target_id  BIGINT                                  NOT NULL,
    detail     VARCHAR(500),
    CONSTRAINT pk_admin_action PRIMARY KEY (id)
);

CREATE INDEX idx_admin_action_created_at ON admin_action (created_at);
