CREATE TABLE worry_post
(
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id     BIGINT                                  NOT NULL,
    content       VARCHAR(500)                            NOT NULL,
    like_count    INTEGER                                 NOT NULL,
    comment_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_worry_post PRIMARY KEY (id)
);

CREATE TABLE worry_post_like
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_worry_post_like PRIMARY KEY (id)
);

CREATE TABLE worry_post_report
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    reporter_id BIGINT                                  NOT NULL,
    post_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_worry_post_report PRIMARY KEY (id)
);

CREATE TABLE worry_comment
(
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    post_id      BIGINT                                  NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    content      VARCHAR(200)                            NOT NULL,
    anonymous_no INTEGER                                 NOT NULL,
    CONSTRAINT pk_worry_comment PRIMARY KEY (id)
);

CREATE TABLE worry_comment_report
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    reporter_id BIGINT                                  NOT NULL,
    comment_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_worry_comment_report PRIMARY KEY (id)
);

ALTER TABLE worry_post_like
    ADD CONSTRAINT uk_worry_post_like_post_id_member_id UNIQUE (post_id, member_id);

ALTER TABLE worry_post_report
    ADD CONSTRAINT uk_worry_post_report_reporter_id_post_id UNIQUE (reporter_id, post_id);

ALTER TABLE worry_comment_report
    ADD CONSTRAINT uk_worry_comment_report_reporter_id_comment_id UNIQUE (reporter_id, comment_id);

CREATE INDEX idx_worry_post_member_id_id ON worry_post (member_id, id);

CREATE INDEX idx_worry_post_like_count_id ON worry_post (like_count DESC, id DESC) WHERE deleted_at IS NULL;

CREATE INDEX idx_worry_post_comment_count_id ON worry_post (comment_count DESC, id DESC) WHERE deleted_at IS NULL;

CREATE INDEX idx_worry_post_like_member_id ON worry_post_like (member_id);

CREATE INDEX idx_worry_post_report_post_id ON worry_post_report (post_id);

CREATE INDEX idx_worry_comment_post_id_id ON worry_comment (post_id, id);

CREATE INDEX idx_worry_comment_member_id ON worry_comment (member_id);

CREATE INDEX idx_worry_comment_report_comment_id ON worry_comment_report (comment_id);
