CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE access_reward
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    platform     VARCHAR(255)                            NOT NULL,
    device_name  VARCHAR(100),
    ip_address   VARCHAR(45)                             NOT NULL,
    accessed_on  date                                    NOT NULL,
    CONSTRAINT pk_access_reward PRIMARY KEY (id)
);

CREATE TABLE ad_reward
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id VARCHAR(64)                             NOT NULL,
    phone_number   VARCHAR(11)                             NOT NULL,
    member_id      BIGINT                                  NOT NULL,
    rewarded_on    date                                    NOT NULL,
    CONSTRAINT pk_ad_reward PRIMARY KEY (id)
);

CREATE TABLE attendance
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    attended_on  date                                    NOT NULL,
    CONSTRAINT pk_attendance PRIMARY KEY (id)
);

CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    content    VARCHAR(1000),
    object_key VARCHAR(255),
    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

CREATE TABLE chat_room
(
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    low_member_id   BIGINT                                  NOT NULL,
    high_member_id  BIGINT                                  NOT NULL,
    last_message_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_chat_room PRIMARY KEY (id)
);

CREATE TABLE chat_room_member
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    room_id              BIGINT                                  NOT NULL,
    member_id            BIGINT                                  NOT NULL,
    last_read_message_id BIGINT                                  NOT NULL,
    unread_count         INTEGER                                 NOT NULL,
    CONSTRAINT pk_chat_room_member PRIMARY KEY (id)
);

CREATE TABLE device_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    platform   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_device_token PRIMARY KEY (id)
);

CREATE TABLE feed_post
(
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    slot_at    TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    object_key VARCHAR(255)                            NOT NULL,
    caption    VARCHAR(30),
    like_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_feed_post PRIMARY KEY (id)
);

CREATE TABLE feed_post_like
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_feed_post_like PRIMARY KEY (id)
);

CREATE TABLE feed_post_report
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    reporter_id BIGINT                                  NOT NULL,
    post_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_feed_post_report PRIMARY KEY (id)
);

CREATE TABLE member
(
    deleted_at                TIMESTAMP(6) WITH TIME ZONE,
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at                TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    phone_number              VARCHAR(11)                             NOT NULL,
    password                  VARCHAR(255)                            NOT NULL,
    gender                    VARCHAR(255)                            NOT NULL,
    nickname                  VARCHAR(10)                             NOT NULL,
    birth_year                INTEGER                                 NOT NULL,
    comment                   VARCHAR(100),
    bio                       VARCHAR(1000),
    role                      VARCHAR(255)                            NOT NULL,
    latitude                  DOUBLE PRECISION,
    longitude                 DOUBLE PRECISION,
    located_at                TIMESTAMP(6) WITH TIME ZONE,
    received_like_count       INTEGER                                 NOT NULL,
    point_balance             INTEGER                                 NOT NULL,
    note_receive_enabled      BOOLEAN                                 NOT NULL,
    feed_notification_enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_block
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    blocker_id        BIGINT                                  NOT NULL,
    blocked_member_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_member_block PRIMARY KEY (id)
);

CREATE TABLE member_favorite
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id          BIGINT                                  NOT NULL,
    favorite_member_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_member_favorite PRIMARY KEY (id)
);

CREATE TABLE member_like
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    liker_id        BIGINT                                  NOT NULL,
    liked_member_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_member_like PRIMARY KEY (id)
);

CREATE TABLE member_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id     BIGINT                                  NOT NULL,
    visibility    VARCHAR(255)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    object_key    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_member_photo PRIMARY KEY (id)
);

CREATE TABLE member_suspension
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    nickname     VARCHAR(10)                             NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    reason       VARCHAR(255)                            NOT NULL,
    started_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    expires_at   TIMESTAMP(6) WITH TIME ZONE,
    detail       VARCHAR(500),
    released_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_member_suspension PRIMARY KEY (id)
);

CREATE TABLE phone_verification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number  VARCHAR(11)                             NOT NULL,
    code          VARCHAR(6)                              NOT NULL,
    ip_address    VARCHAR(45)                             NOT NULL,
    issued_at     TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    attempt_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_phone_verification PRIMARY KEY (id)
);

CREATE TABLE photo_upload
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    object_key VARCHAR(255)                            NOT NULL,
    issued_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    CONSTRAINT pk_photo_upload PRIMARY KEY (id)
);

CREATE TABLE point_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id     BIGINT                                  NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    amount        INTEGER                                 NOT NULL,
    balance_after INTEGER                                 NOT NULL,
    recorded_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    CONSTRAINT pk_point_history PRIMARY KEY (id)
);

CREATE TABLE report
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    reporter_id        BIGINT                                  NOT NULL,
    reported_member_id BIGINT                                  NOT NULL,
    type               VARCHAR(255)                            NOT NULL,
    room_id            BIGINT,
    reason             VARCHAR(255)                            NOT NULL,
    detail             VARCHAR(1000),
    CONSTRAINT pk_report PRIMARY KEY (id)
);

CREATE TABLE report_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_id     BIGINT                                  NOT NULL,
    display_order INTEGER                                 NOT NULL,
    object_key    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_report_photo PRIMARY KEY (id)
);

CREATE TABLE report_snapshot
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_id BIGINT                                  NOT NULL,
    content   JSONB                                   NOT NULL,
    CONSTRAINT pk_report_snapshot PRIMARY KEY (id)
);

CREATE TABLE secret_photo_access
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    viewer_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_secret_photo_access PRIMARY KEY (id)
);

ALTER TABLE access_reward
    ADD CONSTRAINT uk_access_reward_phone_number_accessed_on UNIQUE (phone_number, accessed_on);

ALTER TABLE access_reward
    ADD CONSTRAINT access_reward_platform_check CHECK (platform IN ('IOS', 'ANDROID'));

ALTER TABLE photo_upload
    ADD CONSTRAINT uc_photo_upload_object_key UNIQUE (object_key);

ALTER TABLE ad_reward
    ADD CONSTRAINT uk_ad_reward_transaction_id UNIQUE (transaction_id);

ALTER TABLE attendance
    ADD CONSTRAINT uk_attendance_phone_number_attended_on UNIQUE (phone_number, attended_on);

ALTER TABLE chat_room_member
    ADD CONSTRAINT uk_chat_room_member_room_id_member_id UNIQUE (room_id, member_id);

ALTER TABLE device_token
    ADD CONSTRAINT uk_device_token_token UNIQUE (token);

ALTER TABLE feed_post_like
    ADD CONSTRAINT uk_feed_post_like_post_id_member_id UNIQUE (post_id, member_id);

ALTER TABLE feed_post
    ADD CONSTRAINT uk_feed_post_member_id_slot_at UNIQUE (member_id, slot_at);

ALTER TABLE feed_post_report
    ADD CONSTRAINT uk_feed_post_report_reporter_id_post_id UNIQUE (reporter_id, post_id);

ALTER TABLE member_block
    ADD CONSTRAINT uk_member_block_blocker_id_blocked_member_id UNIQUE (blocker_id, blocked_member_id);

ALTER TABLE member_favorite
    ADD CONSTRAINT uk_member_favorite_member_id_favorite_member_id UNIQUE (member_id, favorite_member_id);

ALTER TABLE member_like
    ADD CONSTRAINT uk_member_like_liker_id_liked_member_id UNIQUE (liker_id, liked_member_id);

ALTER TABLE report_snapshot
    ADD CONSTRAINT uk_report_snapshot_report_id UNIQUE (report_id);

ALTER TABLE secret_photo_access
    ADD CONSTRAINT uk_secret_photo_access_owner_id_viewer_id UNIQUE (owner_id, viewer_id);

CREATE INDEX idx_ad_reward_phone_number_rewarded_on ON ad_reward (phone_number, rewarded_on);

CREATE INDEX idx_chat_message_room_id_id ON chat_message (room_id, id);

CREATE INDEX idx_chat_room_member_member_id ON chat_room_member (member_id);

CREATE INDEX idx_device_token_member_id ON device_token (member_id);

CREATE INDEX idx_feed_post_like_member_id ON feed_post_like (member_id);

CREATE INDEX idx_feed_post_member_id_id ON feed_post (member_id, id);

CREATE INDEX idx_feed_post_report_post_id ON feed_post_report (post_id);

CREATE INDEX idx_member_block_blocked_member_id_blocker_id ON member_block (blocked_member_id, blocker_id);

CREATE INDEX idx_member_favorite_favorite_member_id ON member_favorite (favorite_member_id);

CREATE INDEX idx_member_like_liked_member_id ON member_like (liked_member_id);

CREATE INDEX idx_member_photo_member_id_visibility_display_order ON member_photo (member_id, visibility, display_order);

CREATE INDEX idx_member_suspension_phone_number_type ON member_suspension (phone_number, type);

CREATE INDEX idx_phone_verification_ip_address_issued_at ON phone_verification (ip_address, issued_at);

CREATE INDEX idx_phone_verification_phone_number_issued_at ON phone_verification (phone_number, issued_at);

CREATE INDEX idx_photo_upload_issued_at ON photo_upload (issued_at);

CREATE INDEX idx_point_history_member_id_id ON point_history (member_id, id);

CREATE INDEX idx_point_history_member_id_type_recorded_at ON point_history (member_id, type, recorded_at);

CREATE INDEX idx_report_photo_report_id ON report_photo (report_id, display_order);

CREATE INDEX idx_report_reported_member_id ON report (reported_member_id);

CREATE INDEX idx_secret_photo_access_viewer_id ON secret_photo_access (viewer_id);

CREATE UNIQUE INDEX uk_member_phone_number ON member (phone_number) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_member_nickname ON member (nickname) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_chat_room_members ON chat_room (low_member_id, high_member_id) WHERE deleted_at IS NULL;

CREATE INDEX idx_member_active_located ON member (located_at DESC, id DESC)
    WHERE deleted_at IS NULL AND located_at IS NOT NULL;

CREATE INDEX idx_member_active_gender_located ON member (gender, located_at DESC, id DESC)
    WHERE deleted_at IS NULL AND located_at IS NOT NULL;

CREATE INDEX idx_member_active_like_count ON member (received_like_count DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_member_active_nickname ON member (lower(nickname) text_pattern_ops)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_member_active_location ON member
    USING gist (geography(st_makepoint(longitude, latitude)))
    WHERE deleted_at IS NULL AND latitude IS NOT NULL AND longitude IS NOT NULL;
