CREATE TABLE translation
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_type   VARCHAR(20)                             NOT NULL,
    source_id     BIGINT                                  NOT NULL,
    target_locale VARCHAR(16)                             NOT NULL,
    content       TEXT                                    NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    CONSTRAINT pk_translation PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_translation_source_target
    ON translation (source_type, source_id, target_locale);
