CREATE TABLE member_memo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    target_id  BIGINT                                  NOT NULL,
    content    VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_member_memo PRIMARY KEY (id)
);

ALTER TABLE member_memo
    ADD CONSTRAINT uk_member_memo_owner_id_target_id UNIQUE (owner_id, target_id);

CREATE INDEX idx_member_memo_target_id
    ON member_memo (target_id);
