CREATE TABLE apple_ads_campaign
(
    id         BIGINT                      NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name       VARCHAR(200)                NOT NULL,
    status     VARCHAR(20),
    deleted    BOOLEAN                     NOT NULL,
    CONSTRAINT pk_apple_ads_campaign PRIMARY KEY (id)
);

CREATE TABLE apple_ads_keyword_daily
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    report_date         date                                    NOT NULL,
    campaign_id         BIGINT                                  NOT NULL,
    ad_group_id         BIGINT                                  NOT NULL,
    ad_group_name       VARCHAR(200),
    keyword_id          BIGINT                                  NOT NULL,
    keyword             VARCHAR(200)                            NOT NULL,
    match_type          VARCHAR(20),
    keyword_status      VARCHAR(20),
    bid_amount          NUMERIC(14, 4),
    currency            VARCHAR(3),
    impressions         BIGINT                                  NOT NULL,
    taps                BIGINT                                  NOT NULL,
    total_installs      BIGINT                                  NOT NULL,
    tap_installs        BIGINT                                  NOT NULL,
    view_installs       BIGINT                                  NOT NULL,
    total_new_downloads BIGINT                                  NOT NULL,
    total_redownloads   BIGINT                                  NOT NULL,
    spend               NUMERIC(14, 4)                          NOT NULL,
    CONSTRAINT pk_apple_ads_keyword_daily PRIMARY KEY (id)
);

ALTER TABLE apple_ads_keyword_daily
    ADD CONSTRAINT uk_apple_ads_keyword_daily_keyword_id_report_date UNIQUE (keyword_id, report_date);

CREATE INDEX idx_apple_ads_keyword_daily_campaign_id_report_date ON apple_ads_keyword_daily (campaign_id, report_date);

CREATE TABLE apple_ads_search_term_daily
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    report_date         date                                    NOT NULL,
    campaign_id         BIGINT                                  NOT NULL,
    ad_group_id         BIGINT                                  NOT NULL,
    ad_group_name       VARCHAR(200),
    keyword_id          BIGINT,
    keyword             VARCHAR(200),
    match_type          VARCHAR(20),
    search_term         VARCHAR(200)                            NOT NULL,
    search_term_source  VARCHAR(20),
    country_or_region   VARCHAR(10),
    currency            VARCHAR(3),
    impressions         BIGINT                                  NOT NULL,
    taps                BIGINT                                  NOT NULL,
    total_installs      BIGINT                                  NOT NULL,
    tap_installs        BIGINT                                  NOT NULL,
    view_installs       BIGINT                                  NOT NULL,
    total_new_downloads BIGINT                                  NOT NULL,
    total_redownloads   BIGINT                                  NOT NULL,
    spend               NUMERIC(14, 4)                          NOT NULL,
    CONSTRAINT pk_apple_ads_search_term_daily PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_apple_ads_search_term_daily_term_report_date
    ON apple_ads_search_term_daily (ad_group_id, coalesce(keyword_id, 0), search_term, report_date);

CREATE INDEX idx_apple_ads_search_term_daily_campaign_id_report_date ON apple_ads_search_term_daily (campaign_id, report_date);
