CREATE TABLE access_reward
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    platform     VARCHAR(255)                            NOT NULL,
    device_name  VARCHAR(100),
    ip_address   VARCHAR(45)                             NOT NULL,
    accessed_on  date                                    NOT NULL,
    CONSTRAINT pk_access_reward PRIMARY KEY (id)
);

ALTER TABLE access_reward
    ADD CONSTRAINT uk_access_reward_phone_number_accessed_on UNIQUE (phone_number, accessed_on);

ALTER TABLE access_reward
    ADD CONSTRAINT access_reward_platform_check CHECK (platform IN ('IOS', 'ANDROID'));
