CREATE TABLE apple_ads_action
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    actor_id            BIGINT                                  NOT NULL,
    type                VARCHAR(20)                             NOT NULL,
    campaign_id         BIGINT                                  NOT NULL,
    ad_group_id         BIGINT                                  NOT NULL,
    ad_group_name       VARCHAR(200),
    keyword_id          BIGINT,
    keyword             VARCHAR(200),
    match_type          VARCHAR(20),
    search_term         VARCHAR(200),
    negative_keyword_id BIGINT,
    previous_bid        NUMERIC(14, 4),
    new_bid             NUMERIC(14, 4),
    currency            VARCHAR(3),
    previous_status     VARCHAR(20),
    new_status          VARCHAR(20),
    reason              VARCHAR(500),
    reverted_at         TIMESTAMP(6) WITH TIME ZONE,
    reverted_by_id      BIGINT,
    CONSTRAINT pk_apple_ads_action PRIMARY KEY (id)
);

CREATE INDEX idx_apple_ads_action_created_at ON apple_ads_action (created_at);
