CREATE TABLE contact_block
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    phone_number VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_contact_block PRIMARY KEY (id)
);

ALTER TABLE contact_block
    ADD CONSTRAINT uk_contact_block_member_id_phone_number UNIQUE (member_id, phone_number);

CREATE INDEX idx_contact_block_phone_number ON contact_block (phone_number);
