CREATE TABLE diary
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    entry_date DATE                                    NOT NULL,
    content    TEXT,
    mood       VARCHAR(255),
    CONSTRAINT pk_diary PRIMARY KEY (id)
);

ALTER TABLE diary
    ADD CONSTRAINT uk_diary_member_id_entry_date UNIQUE (member_id, entry_date);

CREATE TABLE diary_attachment
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    diary_id             BIGINT                                  NOT NULL,
    type                 VARCHAR(255)                            NOT NULL,
    object_key           VARCHAR(255)                            NOT NULL,
    thumbnail_object_key VARCHAR(255),
    duration_seconds     INTEGER,
    position             INTEGER                                 NOT NULL,
    CONSTRAINT pk_diary_attachment PRIMARY KEY (id)
);

ALTER TABLE diary_attachment
    ADD CONSTRAINT uk_diary_attachment_object_key UNIQUE (object_key);

CREATE INDEX idx_diary_attachment_diary_id ON diary_attachment (diary_id);
