CREATE TABLE diary
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    entry_date DATE                                    NOT NULL,
    content    TEXT                                    NOT NULL,
    CONSTRAINT pk_diary PRIMARY KEY (id)
);

ALTER TABLE diary
    ADD CONSTRAINT uk_diary_member_id_entry_date UNIQUE (member_id, entry_date);
