CREATE TABLE access_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    platform     VARCHAR(255)                            NOT NULL,
    device_name  VARCHAR(100),
    ip_address   VARCHAR(45)                             NOT NULL,
    accessed_on  date                                    NOT NULL,
    CONSTRAINT pk_access_log PRIMARY KEY (id)
);

ALTER TABLE access_log
    ADD CONSTRAINT uk_access_log_member_id_accessed_on UNIQUE (member_id, accessed_on);

CREATE INDEX idx_access_log_created_at ON access_log (created_at);

CREATE TABLE nickname_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    nickname   VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_nickname_history PRIMARY KEY (id)
);

CREATE INDEX idx_nickname_history_member_id ON nickname_history (member_id);
CREATE INDEX idx_nickname_history_nickname ON nickname_history (nickname);
