CREATE TABLE ai_reply_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ai_member_id      BIGINT                                  NOT NULL,
    room_id           BIGINT                                  NOT NULL,
    message_id        BIGINT                                  NOT NULL,
    prompt_tokens     INTEGER                                 NOT NULL,
    completion_tokens INTEGER                                 NOT NULL,
    model             VARCHAR(100),
    created_at        TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_ai_reply_log_ai_member_id_created_at ON ai_reply_log (ai_member_id, created_at);
CREATE INDEX idx_ai_reply_log_room_id_created_at ON ai_reply_log (room_id, created_at);
CREATE INDEX idx_ai_reply_log_created_at ON ai_reply_log (created_at);
