CREATE TABLE ai_reply_bubble
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id      BIGINT                                  NOT NULL,
    ai_member_id BIGINT                                  NOT NULL,
    content      VARCHAR(1000)                           NOT NULL,
    due_at       TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_ai_reply_bubble_due_at ON ai_reply_bubble (due_at);
