CREATE TABLE profile_view
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    viewer_id        BIGINT                                  NOT NULL,
    viewed_member_id BIGINT                                  NOT NULL,
    viewed_at        TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    CONSTRAINT pk_profile_view PRIMARY KEY (id)
);

ALTER TABLE profile_view
    ADD CONSTRAINT uk_profile_view_viewer_id_viewed_member_id UNIQUE (viewer_id, viewed_member_id);

CREATE INDEX idx_profile_view_viewed_member_id_viewed_at_id
    ON profile_view (viewed_member_id, viewed_at, id);
