spring:
  application:
    name: server

  profiles:
    default: local

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
